repos:
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit -r lesson_04_face_control/requirements.txt
        language: system
        files: ^lesson_04_face_control/requirements\.txt$
